# Configuración liviana para la Q8 A33
deband=no
keep-open=no

# OPTIMIZACIÓN Q8 A33

# MODO LIVIANO Q8 A33
vo=x11
hwdec=no
framedrop=vo
scale=bilinear
dscale=bilinear
sws-scaler=fast-bilinear
vd-lavc-fast=yes
vd-lavc-skiploopfilter=all
demuxer-max-bytes=8MiB
demuxer-max-back-bytes=1MiB
cache-secs=20
