#!/bin/sh
set -eu

DRIVER=/sys/bus/serial/drivers/hci_uart_h5
DEVICE=serial0-0

systemctl stop bluetooth.service

if [ -L "$DRIVER/$DEVICE" ]; then
    echo "$DEVICE" > "$DRIVER/unbind"
fi

sleep 2
echo "$DEVICE" > "$DRIVER/bind"

for I in 1 2 3 4 5 6 7 8 9 10; do
    [ -d /sys/class/bluetooth/hci0 ] && break
    sleep 1
done

systemctl start bluetooth.service
