ThemeAuthor=                            "BlueScorpio_7"
ThemeDescription=                       "CrystalBlue"
License=                                "GPL"

Look=                                   "flat"
Gradients=                              "menubg.xpm dialogbg.xpm workspacebuttonbg.xpm workspacebuttonactive.xpm buttonA.xpm buttonI.xpm"

#Buttons
RolloverButtonsSupported=               1
TitleButtonsSupported=                  "xmirs"
TitleButtonsLeft=                       "r"
TitleButtonsRight=                      "xmi"

TaskBarClockLeds=                       1
TrayDrawBevel=                          0

#Borders
BorderSizeX=                            5
BorderSizeY=                            5
DlgBorderSizeX=                         5
DlgBorderSizeY=                         5
CornerSizeX=                            24
CornerSizeY=                            24
TitleBarHeight=40
TitleBarJustify=                        50
TitleBarVertOffset=                     -2
ScrollBarX=24
ScrollBarY=24

#Icons
MenuIconSize=24
SmallIconSize=24
LargeIconSize=48
HugeIconSize=64

#DialogBox

ColorDialog=                            "rgb:45/55/A4"
ColorDialogSelectionText=               "rgb:C0/C0/C0"

#Taskbar
TaskbuttonIconOffset=                   10
ColorDefaultTaskBar="rgb:0B/16/2B"
ColorToolButton="rgb:12/25/48"
ColorToolButtonText=                    "rgb:C0/C0/C0"
ColorActiveButton="rgb:1C/3E/70"
ColorNormalButton="rgb:12/25/48"
ColorNormalWorkspaceButton=             "rgb:2A/39/83"
ColorNormalWorkspaceButtonText=         "rgb:C0/C0/C0"

ColorActiveWorkspaceButton=             "rgb:2A/39/83"
ColorActiveWorkspaceButtonText=         "rgb:14/20/5E"
ColorNormalButtonText=                  "rgb:C0/C0/C0"
ColorActiveButtonText=                  "rgb:C0/C0/C0"
ColorActiveTaskBarApp=                  "rgb:2A/39/83"
ColorActiveTaskBarAppText=              "rgb:14/20/5E"

ColorMinimizedTaskBarApp=               "rgb:2A/39/83"
ColorMinimizedTaskBarAppText=           "rgb:C0/C0/C0"
ColorNormalTaskBarApp=                  "rgb:2A/39/83"
ColorNormalTaskBarAppText=              "rgb:C0/C0/C0"
ColorInvisibleTaskBarAppText=           "rgb:C0/C0/C0"

#Menu
ColorActiveMenu=                        "rgb:45/55/A4"
ColorActiveMenuItem="rgb:24/4E/86"
ColorNormalMenu="rgb:12/1B/2E"
ColorNormalMenuItem=                    "rgb:C0/C0/C0"
ColorNormalMenuItemText="rgb:F0/F4/FF"
ColorActiveMenuItemText="rgb:FF/FF/FF"
ColorDisabledMenuItemText=              "rgb:80/80/80"
ColorDisabledMenuItemShadow=            "rgb:00/00/00"

#TitleBox
ColorNormalBorder=                      "rgb:2A/39/83"
ColorActiveBorder=                      "rgb:2A/39/83"
ColorNormalTitleBarText=                "rgb:F0/F0/F0"
ColorActiveTitleBarText=                "rgb:14/20/5E"
ColorNormalTitleBarShadow=              "rgb:14/20/5E"
ColorActiveTitleBarShadow=              "rgb:FF/FF/FF"

#Move
ColorMoveSizeStatus=                    "rgb:45/55/A4"
ColorMoveSizeStatusText=                "rgb:C0/C0/C0"

#Tooltip
ColorToolTip=                           "rgb:45/55/A4"
ColorToolTipText=                       "rgb:C0/C0/C0"

#QuickSwitch
ColorQuickSwitch=                       "rgb:45/55/A4"
ColorQuickSwitchText=                   "rgb:C0/C0/C0"

#ListBox
ColorListBox=                           "rgb:45/55/A4"
ColorListBoxText=                       "rgb:C0/C0/C0"
ColorListBoxSelection=                  "rgb:C0/C0/C0"
ColorListBoxSelectionText=              "rgb:45/55/A4"

#Label
ColorLabel=                             "rgb:45/55/A4"
ColorLabelText=                         "rgb:C0/C0/C0"

#Clock
ColorClock=                             "rgb:45/55/A4"
ColorClockText=                         "rgb:C0/C0/C0"

#CPUMonitor
ColorCPUStatusIdle=                     "rgb:14/20/5E"
ColorCPUStatusUser=                     "rgb:6C/7A/C3"
ColorCPUStatusSystem=                   "rgb:C0/C0/C0"
ColorCPUStatusInterrupts=               "rgb:FF/00/0F"
ColorCPUStatusIoWait=                   "rgb:FF/FF/FF"
ColorCPUStatusSoftIrq=                  "rgb:00/DE/FF"
ColorCPUStatusNice=                     "rgb:8C/93/9A"

#Net
ColorNetIdle=                           "rgb:14/20/5E"
ColorNetSend=                           "rgb:C0/C0/C0"
ColorNetReceive=                        "rgb:6C/7A/C3"

#APM
ColorApm=                               "rgb:45/55/A4"
ColorApmText=                           "rgb:C0/C0/C0"

#Memory Manager
ColorMEMStatusFree=                     "rgb:14/20/5E"
ColorMEMStatusCached=                   "rgb:C0/C0/C0"
ColorMEMStatusUser=                     "rgb:6C/7A/C3"
ColorMEMStatusBuffers=                  "rgb:00/00/00"

#Input
ColorInput=                             "rgb:2A/39/83"
ColorInputText=                         "rgb:C0/C0/C0"
ColorInputSelection=                    "rgb:14/20/5E"
ColorInputSelectionText=                "rgb:C0/C0/C0"

#ScrollBar
ColorScrollBar=                         "rgb:C0/C0/C0"
ColorScrollBarButton=                   "rgb:C0/C0/C0"
ColorScrollBarSlider=                   "rgb:45/55/A4"
ColorScrollBarArrow=                    "rgb:45/55/A4"
ColorScrollBarButtonArrow=              "rgb:C0/C0/C0"
ColorScrollBarInactiveArrow=            "rgb:C0/C0/C0"

#Fonts
TitleFontNameXft="DejaVu Sans:size=16:bold"
StatusFontNameXft="DejaVu Sans:size=16:bold"
MenuFontNameXft="DejaVu Sans:size=16:bold"
NormalTaskBarFontNameXft="DejaVu Sans:size=16:bold"
ActiveTaskBarFontNameXft="DejaVu Sans:size=16:bold"
ListBoxFontNameXft="DejaVu Sans:size=16:bold"
ToolTipFontNameXft="DejaVu Sans:size=16:bold"
QuickSwitchFontNameXft="DejaVu Sans:size=17:bold"
ClockFontNameXft="DejaVu Sans:size=16:bold"

#Desktop
DesktopBackgroundColor=                 "rgb:25/33/79"
DesktopTransparencyColor=               "rgb:25/33/79"
